### PR TITLE
Expand play mode game panel focus options by a focus back option

### LINKED ISSUE #2440: [Proposal] After entering play mode and exiting, switch back to previous editor
**Issue description:**

Picture this: Your iterating over an asset and want to enter play mode to see the asset in game.
So you enter play mode, check your asset, see something you want to change and then exit play mode.

Now you have to click on the editor of your asset because on exiting play mode, the game panel stays focused.
This may sound like a minor and easy to overcome issue, but it's really limiting iteration speed and introduces an unnecessary click.

https://github.com/FlaxEngine/FlaxEngine/assets/111653551/6fffaa4a-2d37-4025-8580-d4a413dd8af9

My fix would be that the editor remembers which asset editor was last focused before entering play mode and then re- focuses that editor once play mode is exited.

An editor setting may be useful here, because people may expect the current behavior.

**Steps to reproduce:**

1. Open an asset in an editor
2. Dock that editor in the same areas as the Game panel
3. Enter play mode
4. Watch how the editor does not go back to the previous editor but stays in the Game panel

**Minimal reproduction project:**

none

**Flax version:**

1.8

### PR DESCRIPTION
**Pull request by xxSeys1**
image

image

Closes #2440.

### CODE REVIEW

File: Source/Editor/Options/InterfaceOptions.cs [hunk 1]
```diff
@@ -138,6 +138,27 @@ public enum ValueFormattingType
...
+        {
+            /// <summary>
+            /// Don't change any focus.
+            /// </summary>
+            None,
+
+            /// <summary>
+            /// Focus the Game panel.
+            /// </summary>
+            GamePanel,
```
Comment (mafiesto4) [inline Source/Editor/Options/InterfaceOptions.cs:154]: Use `GameWindow` name to match naming in Editor.

File: Source/Editor/Options/InterfaceOptions.cs [hunk 2]
```diff
@@ -138,6 +138,27 @@ public enum ValueFormattingType
...
+
+            /// <summary>
+            /// Focus the Game panel. On play mode end focus the previous panel again.
+            /// </summary>
+            GamePanelThenBack,
```
Comment (mafiesto4) [inline Source/Editor/Options/InterfaceOptions.cs:159]: Use `GameWindowThenRestore` name to match naming in Editor.

File: Source/Editor/Windows/GameWindow.cs [hunk 3]
```diff
@@ -39,6 +39,28 @@ public class GameWindow : EditorWindow
         private bool _useAspect = false;
         private bool _freeAspect = true;
 
+        private List<PlayModeFocusOptions> _focusOptions = new List<PlayModeFocusOptions>()
```
Comment (mafiesto4) [inline Source/Editor/Windows/GameWindow.cs:42]: Update `Name` and `Tooltip` texts to match `Game Window` naming (instead of `Panel`).

File: Source/Editor/Options/InterfaceOptions.cs [hunk 4]
```diff
@@ -341,11 +362,11 @@ public FontReference OutputLogTextFont
...
         /// <summary>
-        /// Gets or sets a value indicating whether auto-focus game window on play mode start.
+        /// Gets or sets a value indicating what panel should be focused when play mode start.
         /// </summary>
-        [DefaultValue(true)]
-        [EditorDisplay("Play In-Editor", "Focus Game Window On Play"), EditorOrder(500), Tooltip("Determines whether auto-focus game window on play mode start.")]
-        public bool FocusGameWinOnPlay { get; set; } = true;
+        [DefaultValue(PlayModeFocus.GamePanel)]
+        [EditorDisplay("Play In-Editor", "Focus On Play"), EditorOrder(500), Tooltip("Set what panel to focus on play mode start.")]
+        public PlayModeFocus FocusOnPlayMode { get; set; } = PlayModeFocus.GamePanel;
```
Comment (mafiesto4) [inline Source/Editor/Options/InterfaceOptions.cs:369]: I think it would be nice to leave auto-upgrader for old option so people who disabled it will get the same logic. Try adding:
```cs
// [Deprecated in v1.10]
[Serialize, Obsolete, NoUndo]
private bool FocusGameWinOnPlay
{
    get => throw new Exception();
    set
    {
        // Upgrade value
        FocusOnPlayMode = value ? PlayModeFocus.GamePanel : PlayModeFocus.None;
    }
}
```

**Review by mafiesto4 — CHANGES_REQUESTED** [review]

File: Source/Editor/Options/InterfaceOptions.cs (hunk 4 above)
Comment (xxSeys1) [reply Source/Editor/Options/InterfaceOptions.cs]: Added in https://github.com/FlaxEngine/FlaxEngine/pull/2994/commits/88215ca3f0e3e54ce8a29db1b5bfdde2c476f494.

Thanks for the reviews :)

File: Source/Editor/Options/InterfaceOptions.cs (hunk 2 above)
Comment (xxSeys1) [reply Source/Editor/Options/InterfaceOptions.cs]: Added in https://github.com/FlaxEngine/FlaxEngine/pull/2994/commits/2721364df6be1c5d38ebcf1055ebbc2beda5863e.

File: Source/Editor/Options/InterfaceOptions.cs (hunk 1 above)
Comment (xxSeys1) [reply Source/Editor/Options/InterfaceOptions.cs]: Added in https://github.com/FlaxEngine/FlaxEngine/pull/2994/commits/2721364df6be1c5d38ebcf1055ebbc2beda5863e.

**Review by mafiesto4 — APPROVED** [review]
