### PR TITLE
Fix android build on .net9 and use DotNet version that is found by build tool path.

### LINKED ISSUE #3140: Trying to run build on android device fails due to missing libs
**Issue description:**
I am running the master branch and I have both .net 8 and .net 9 installed on my PC. When it builds for android it looks like it is trying to use .net 9 for some reason. 

When trying to run the built app on an android device I get this error: 
```
01-07 21:16:36.426  7286  7314 I Flax    : [ 00:00:00.286 ]: [Info] Initialize Windows Manager...
01-07 21:16:36.426  7286  7314 I Flax    : [ 00:00:00.286 ]: [Info] Initialize Scripting...
01-07 21:16:36.755  7286  7314 I Flax    : [ 00:00:00.615 ]: [Info] Mono runtime version: 9.0.0.0 (9.0.24.52809 @Commit: 9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3)
01-07 21:16:36.968  7286  7314 I Flax    : [ 00:00:00.827 ]: [Warning] [Mono] DllImport unable to load library 'libSystem.Globalization.Native'.
01-07 21:16:36.969  7286  7314 I Flax    : [ 00:00:00.829 ]: [Warning] [Mono] DllImport unable to load library 'libSystem.Globalization.Native'.
01-07 21:16:36.973  7286  7314 I Flax    : [ 00:00:00.833 ]: [Warning] [Mono] DllImport unable to load library 'libSystem.Globalization.Native'.
01-07 21:16:37.082  7286  7314 I Flax    : [ 00:00:00.942 ]: [Warning] [Mono] DllImport unable to load library 'libSystem.Globalization.Native'.
01-07 21:16:37.083  7286  7314 I Flax    : [ 00:00:00.943 ]: [Warning] [Mono] DllImport unable to load library 'libSystem.Globalization.Native'.
01-07 21:16:37.086  7286  7314 I Flax    : [ 00:00:00.946 ]: [Warning] [Mono] DllImport unable to load library 'libSystem.Globalization.Native'.
01-07 21:16:37.118  7286  7314 I Flax    : [ 00:00:00.978 ]: [Warning] [Mono] Process terminated.
01-07 21:16:37.119  7286  7314 I Flax    : [ 00:00:00.979 ]: [Warning] [Mono] Encountered infinite recursion while looking up resource 'Arg_DllNotFoundException' in System.Private.CoreLib. Verify the installation of .NET is complete and does not need repairing, and that the state of the process has not become corrupted.

```

It looks like it built with .net 9 and is missing some libs. Looking through the source code, these libs are only being looked for in the .net 8 files, so it makes sense that it is missing. I believe the main issue is that the build is using .net 9 because it is installed, but not including the .net 9 libs it needs.

**Flax version:**
master branch.

### PR DESCRIPTION
**Pull request by Tryibion**
Fix #3140 by adding `libSystem.Globalization.Native.so` to deploy list.

This also adds finding the .net version that is returned by the build tool to use the correct folders for getting build libs. Ex: with .net9 installed, the building wants to use it but the libs were being looked for in the .net8 folder which doesnt exist in the 9.0.0 runtime folder.

### CODE REVIEW

File: Source/Editor/Cooker/Steps/DeployDataStep.cpp [hunk 1]
```diff
@@ -214,6 +214,30 @@ bool DeployDataStep::Perform(CookingData& data)
...
+                for (int i = 0; i < pathParts.Count(); i++)
+                {
+                    if (pathParts[i] == TEXT("runtimes"))
+                    {
+                        Array<String> versionParts;
+                        pathParts[i - 1].Split('.', versionParts);
+                        const String majorVersion = versionParts[0].TrimTrailing();
+                        uint32 versionNum;
+                        StringUtils::Parse(*majorVersion, majorVersion.Length(), &versionNum);
+                        if (versionNum < GAME_BUILD_DOTNET_RUNTIME_MAX_VER || versionNum > GAME_BUILD_DOTNET_RUNTIME_MIN_VER) // Check for major part
```
Comment (mafiesto4) [inline Source/Editor/Cooker/Steps/DeployDataStep.cpp:230]: You could use `Math::IsInRange(versionNum, GAME_BUILD_DOTNET_RUNTIME_MIN_VER, GAME_BUILD_DOTNET_RUNTIME_MAX_VER)` to check for range.

File: Source/Editor/Cooker/Steps/DeployDataStep.cpp [hunk 2]
```diff
@@ -214,6 +214,30 @@ bool DeployDataStep::Perform(CookingData& data)
...
+                Array<String> pathParts;
+                srcDotnet.Split('/', pathParts);
+                String version;
+                for (int i = 0; i < pathParts.Count(); i++)
+                {
+                    if (pathParts[i] == TEXT("runtimes"))
+                    {
+                        Array<String> versionParts;
+                        pathParts[i - 1].Split('.', versionParts);
+                        const String majorVersion = versionParts[0].TrimTrailing();
```
Comment (mafiesto4) [inline Source/Editor/Cooker/Steps/DeployDataStep.cpp:227]: This could check if array is non-empty to prevent errors in case dotnet changes folders structure.

**Review by mafiesto4 — CHANGES_REQUESTED** [review]

**Review by mafiesto4 — APPROVED** [review]
